CREATE DATABASE COPROTECT;

USE COPROTECT;

CREATE TABLE Roles (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Rol VARCHAR(10) CHECK (Rol IN ('CLIENTE', 'EMPLEADO'))
);

INSERT INTO Roles (Rol) VALUES ('CLIENTE'), ('EMPLEADO');

CREATE TABLE Usuarios (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Nombre VARCHAR(50),
    RolID INT,
    FOREIGN KEY (RolID) REFERENCES Roles(ID)
);

CREATE TABLE Clientes (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    UsuarioID INT,
    FOREIGN KEY (UsuarioID) REFERENCES Usuarios(ID)
);

CREATE TABLE Empleados (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    UsuarioID INT,
    FOREIGN KEY (UsuarioID) REFERENCES Usuarios(ID)
);

CREATE TABLE Equipos (
    ID INT PRIMARY KEY AUTO_INCREMENT,
    Estado VARCHAR(15) CHECK (Estado IN ('EN REPARACION', 'REPARADO')),
    ClienteID INT,
    FOREIGN KEY (ClienteID) REFERENCES Clientes(ID)
);

