CREATE TABLE USUARIOS (
    ID INT PRIMARY KEY,
    Nombre VARCHAR(20) ,
    Apellido VARCHAR(20),
    Edad INT
);

CREATE TABLE tbl_EQUIPOS (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    fecha DATE ,
    cantidad INT,
    estado TINYINT 
);

CREATE TABLE PERSONAS (
    ID INT PRIMARY KEY,
    User VARCHAR(10),
    Pass VARCHAR(100),
    id_PERSONAS INT,
    id_EQUIPOS INT,
    CONSTRAINT fk_USUARIOS_ssh FOREIGN KEY (id_PERSONAS) REFERENCES USUARIOS(ID),
    CONSTRAINT fk_EQUIPOS_ssh FOREIGN KEY (id_EQUIPOS) REFERENCES tbl_EQUIPOS(ID)
);

